spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/anilallewar/sample-config
          uri: /home/harsh/Work/Quovantis/microservice/QuoMicroserviceApp/configuration-server/config
          basedir: /home/harsh/Work/Quovantis/microservice/QuoMicroserviceApp/configuration-server/config
# While in development mode, you can configure the config server to pick up configuration files from
# the file system

#           uri: /home/harsh/Work/Quovantis/microservice/QuoMicroserviceApp/configuration-server/config
# Defines the port where the config server is running so that rest of the services can pick up
# their external configurations
server:
  port: 8888